messages:
  hello: Hello world!

environment: dev
maxLength: 100
dateFormat: yyyy-MM-dd'T'HH:mmZ

# mongoDB setting
mongo:
  host: localhost
  port: 27017
  database: dropwizard

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  appenders:
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./log/application.log
      archivedLogFilenamePattern: ./log/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB